//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.RFIDs = new HashSet<RFID>();
        }
    
        public long BookID { get; set; }
        public string ISBN { get; set; }
        public string BookTitle { get; set; }
        public string CallNumber { get; set; }
        public string SubjectCode { get; set; }
        public string Author { get; set; }
        public string PublisherID { get; set; }
        public decimal Price { get; set; }
        public short TotalCopy { get; set; }
        public string PublishedYear { get; set; }
        public string Edition { get; set; }
    
        public virtual BookSubject BookSubject { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFID> RFIDs { get; set; }
    }
}
