//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSubjects
    {
        public BookSubjects()
        {
            this.Books = new HashSet<Books>();
        }
    
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
    }
}
