//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string FacultyCode { get; set; }
        public string FacultyName { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
