//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTrans
    {
        public long TransactionID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime DateDue { get; set; }
        public short BorrowedQty { get; set; }
    }
}
