//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTran
    {
        public IssueTran()
        {
            this.Status = "out";
        }
    
        public long TransactionID { get; set; }
        public string RFID { get; set; }
        public long MemberID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateActualReturned { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Member Members { get; set; }
        public virtual RFIDTag RFIDs { get; set; }
    }
}
