//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA45Team07B_LibraryEntities : DbContext
    {
        public SA45Team07B_LibraryEntities()
            : base("name=SA45Team07B_LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Books> Books { get; set; }
        public DbSet<BookSubjects> BookSubjects { get; set; }
        public DbSet<Faculties> Faculties { get; set; }
        public DbSet<IssueTrans> IssueTrans { get; set; }
        public DbSet<MemberCategories> MemberCategories { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<RFIDs> RFIDs { get; set; }
        public DbSet<StockAdjustments> StockAdjustments { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
