//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA45Team07B_LibraryEntities : DbContext
    {
        public SA45Team07B_LibraryEntities()
            : base("name=SA45Team07B_LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Books { get; set; }
        public DbSet<BookSubject> BookSubjects { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<IssueTran> IssueTrans { get; set; }
        public DbSet<MemberCategories> MemberCategories { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Publisher> Publishers { get; set; }
        public DbSet<RFIDTag> RFIDs { get; set; }
        public DbSet<StockAdjustment> StockAdjustments { get; set; }
    }
}
