//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberCategory()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string MemberType { get; set; }
        public string CategoryName { get; set; }
        public short LoanEntitlement { get; set; }
        public short LoanPeriod { get; set; }
        public decimal FinePerDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
