//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDs
    {
        public RFIDs()
        {
            this.IssueTrans = new HashSet<IssueTrans>();
            this.StockAdjustments = new HashSet<StockAdjustments>();
        }
    
        public string RFID { get; set; }
        public long BookID { get; set; }
        public string Discontinued { get; set; }
        public Nullable<long> LastTransactionID { get; set; }
        public string Availability { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ICollection<IssueTrans> IssueTrans { get; set; }
        public virtual ICollection<StockAdjustments> StockAdjustments { get; set; }
    }
}
