//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public string RFID { get; set; }
        public System.DateTime DateAdjusted { get; set; }
        public short QtyAdjusted { get; set; }
        public string Remarks { get; set; }
    
        public virtual RFIDTag RFIDs { get; set; }
    }
}
