//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45Team07B
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDetails
    {
        public long TransactionID { get; set; }
        public long BookID { get; set; }
        public System.DateTime DateReturned { get; set; }
        public string ReturnedStatus { get; set; }
        public string Remarks { get; set; }
    }
}
